# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hetty < Formula
  desc "An HTTP toolkit for security research."
  homepage "https://hetty.xyz"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dstotijn/hetty/releases/download/v0.7.0/hetty_0.7.0_macOS_arm64.tar.gz"
      sha256 "33b16f546e10abd971958d7b49b9d2dea2989d4f33f6d6b05109ae4fd7073d25"

      def install
        bin.install "hetty"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dstotijn/hetty/releases/download/v0.7.0/hetty_0.7.0_macOS_x86_64.tar.gz"
      sha256 "d8d1c6ce383c6c1e224c53b847e4690ec43c929e715aa5b286894adc3f2c9963"

      def install
        bin.install "hetty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dstotijn/hetty/releases/download/v0.7.0/hetty_0.7.0_Linux_arm64.tar.gz"
      sha256 "312405eebffd560b9b36e1640f7ae87d62b41078fddf5962633d6d09fe08b925"

      def install
        bin.install "hetty"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dstotijn/hetty/releases/download/v0.7.0/hetty_0.7.0_Linux_x86_64.tar.gz"
      sha256 "1bf1501907beb25b550837813fa800b9a56532b0b447a617c133c07ddfbbc18d"

      def install
        bin.install "hetty"
      end
    end
  end

  test do
    system "#{bin}/hetty -v"
  end
end
