# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hetty < Formula
  desc "An HTTP toolkit for security research."
  homepage "https://hetty.xyz"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dstotijn/hetty/releases/download/v0.6.0/hetty_0.6.0_macOS_arm64.tar.gz"
      sha256 "57711ca4fd8b3d57f74e82495e0a1561f69c6eb6c450c6266a94de96bdc19891"

      def install
        bin.install "hetty"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dstotijn/hetty/releases/download/v0.6.0/hetty_0.6.0_macOS_x86_64.tar.gz"
      sha256 "3d217d64351c81ef5617946c0f74655ebe32432d3732aec1cf93d866354b7bb2"

      def install
        bin.install "hetty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dstotijn/hetty/releases/download/v0.6.0/hetty_0.6.0_Linux_arm64.tar.gz"
      sha256 "28634b5d444a3d2e0b806da6605e81faa9f46b86d26158bea7a24caaf7404027"

      def install
        bin.install "hetty"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dstotijn/hetty/releases/download/v0.6.0/hetty_0.6.0_Linux_x86_64.tar.gz"
      sha256 "8775eec845f6ec1485ab7c19672a32b9fcfc26ce73b91729e9f0e97a81246299"

      def install
        bin.install "hetty"
      end
    end
  end

  test do
    system "#{bin}/hetty -v"
  end
end
